theme = "kurtisfields"
baseurl = "https://kfields.netlify.com"
languageCode = "en-us"
title = "Kurtis Fields"

[[menu.main]]
  name = "Services"
  url = "/services/"

[[menu.main]]
  name = "Fees"
  url = "/fees/"
